### ISSUE TITLE
iOS 10

### ISSUE THREAD

**Issue by Narcisss** [ReDetection/NGTMap#1]
Когда сделаете поддержку iOS 10? На этой версии приложение вылетает, даже после сегодняшнего обновления.

**Comment by ReDetection** [comment]
Поддержка iOS 10 реализована, но, как верно замечено, она ещё не доступна в AppStore. Я могу добавить вас в список бета-тестеров, мне только нужен email, на который высылать приглашение в Apple Testflight. Можете написать мне на sbuglakov+ngtmap@xiag.ch или вконтакте https://vk.com/redetection, я добавлю.

**Comment by ReDetection** [comment]
Ок, уже полнедели в AppStore. Закрываю проблему
